name: Test

on:
  push:
    branches:
      - main
      - v1-stable
  pull_request:
    branches:
      - main
      - v1-stable
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  rspec:
    name: Ruby ${{matrix.ruby-version}} (${{ matrix.gemfile }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - rails_5.1
          - rails_5.2
          - rails_6.0
          - rails_6.1
          - rails_7.0
          - rails_7.1
          - rails_7.2
          - rails_8.0
          - rails_8.1
        ruby-version:
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"
        exclude:
          # Ruby 4.0
          - gemfile: rails_5.1
            ruby-version: "4.0"
          - gemfile: rails_5.2
            ruby-version: "4.0"
          - gemfile: rails_6.0
            ruby-version: "4.0"
          - gemfile: rails_6.1
            ruby-version: "4.0"

    steps:
      - uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

      - name: RSpec
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
        run: bundle exec rspec
