name: Test

on:
  push:
    branches:
      - main
      - v1-stable
  pull_request:
    branches:
      - main
      - v1-stable
  workflow_dispatch:

# permissions:
#   contents: read

jobs:
  rspec:
    name: Ruby ${{matrix.ruby-version}} (${{ matrix.gemfile }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - rails_5.1
          - rails_5.2
          - rails_6.0
          - rails_6.1
          - rails_7.0
          - rails_7.1
          - rails_7.2
          - rails_8.0
          - rails_8.1
        ruby-version:
          - "3.2"
          - "3.3"
          - "3.4"
          - "3.5.0-preview1"
          - "4.0.0-preview2"
        exclude:
          - gemfile: rails_5.1
            ruby-version: "3.5.0-preview1"
          - gemfile: rails_5.2
            ruby-version: "3.5.0-preview1"
          - gemfile: rails_6.0
            ruby-version: "3.5.0-preview1"
          - gemfile: rails_6.1
            ruby-version: "3.5.0-preview1"
          - gemfile: rails_7.0
            ruby-version: "3.5.0-preview1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

      - name: RSpec
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
        run: bundle exec rspec
